import Head from "next/head";
import Banner from "./component/banner";
import { ContactPage } from "./component/contact/Index";


export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact: Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactPage />

      </>
  );
}
